services:
  database:
    image: "postgres"
    environment:
      POSTGRES_DB: esg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 99009900
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    image: "studentitp:latest"
    links:
      - "database:db"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
