# Generated by Django 4.2 on 2024-03-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esg_app", "0002_datavalue_framework_frameworkmetric_indicator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="unit",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
