# Generated by Django 4.2 on 2024-03-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esg_app", "0003_indicator_unit"),
    ]

    operations = [
        migrations.RemoveField(model_name="metric", name="framework",),
    ]
